---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jupyter
  namespace: jhub
spec:
  releaseName: jupyterhub
  chart:
    repository: https://jupyterhub.github.io/helm-chart/
    name: jupyterhub
    version: 0.9.0
  values:
    auth:
      type: github
      github:
        clientId: "Iv1.2cfe53cc93b7f46c"
        clientSecret: "5cb76f34ad66b9850bdbfba7c136c813e2d21729"
        callbackUrl: "http://jhub.omarlari.com/hub/oauth_callback"
      admin:
        access: true
        users:
          - omarlari
          # ...
      whitelist:
        users:
          - omarlari
          # ...
    proxy:
      secretToken: "331564c1d27fe891eefd7ab04eb3073ca93c74215b1fbd538d7319752c1f47ce"
      service:
        type: LoadBalancer
        #type: NodePort
        #nodePorts:
        #  http: 30080
        #  https: 30443
    singleuser:
      # Defines the default image
      image:
        name: jupyter/minimal-notebook
        tag: 2343e33dec46
      profileList:
        - display_name: "Minimal environment"
          description: "To avoid too much bells and whistles: Python."
          default: true
        - display_name: "Datascience environment"
          description: "If you want the additional bells and whistles: Python, R, and Julia."
          kubespawner_override:
            image: jupyter/datascience-notebook:2343e33dec46
        - display_name: "Spark environment"
          description: "The Jupyter Stacks spark image!"
          kubespawner_override:
            image: jupyter/all-spark-notebook:2343e33dec46
        - display_name: "Learning Data Science"
          description: "Datascience Environment with Sample Notebooks"
          kubespawner_override:
            image: jupyter/datascience-notebook:2343e33dec46
            lifecycle_hooks:
              postStart:
                exec:
                  command:
                    - "sh"
                    - "-c"
                    - >
                      gitpuller https://github.com/data-8/materials-fa17 master materials-fa;
